{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mineos.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mineos.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    {{- with .Values.ingress.adminPage }}
    - hosts:
      - {{ .host | quote }}
      secretName: {{ .host }}-tls
    {{- end }}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- with .Values.ingress.adminPage }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .baseUrl }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-admin
                port:
                  number: 8443
              {{- else }}
              serviceName: {{ $fullName }}-admin
              servicePort: 8443
              {{- end }}
    {{- end }}
---
{{- if .Values.httpServices }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "mineos.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    {{- range .Values.httpServices }}
    - hosts:
      - {{ .host | quote }}
      secretName: {{ .host }}-tls
    {{- end }}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.httpServices }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "{{ .path }}"
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-http
                port:
                  number: {{ .port }}
              {{- else }}
              serviceName: {{ $fullName }}-http
              servicePort: {{ .port }}
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}
