apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jellyfin.serviceAccountName" . }}
      securityContext:
        {{- with .Values.podSecurityContext }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.hardwareAcceleration.intel.enabled }}
        supplementalGroups:
          - {{ required "You need to define the render group id." .Values.hardwareAcceleration.intel.renderGroupId }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.hardwareAcceleration.intel.enabled }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - groupadd -g {{ .Values.hardwareAcceleration.intel.renderGroupId }} render;
                  - usermod -a -G render hotio;
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.hardwareAcceleration.intel.enabled }}
          securityContext:
            privileged: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /config
              name: config
            {{- if .Values.hardwareAcceleration.intel.enabled }}
            - name: render-device
              mountPath: {{ .Values.hardwareAcceleration.intel.renderDevicePath }}
            {{- end }}
      initContainers:
        - name: config
          image: pipelinecomponents/xmllint:0.8.1
          securityContext:
            runAsUser: 1000 # Find a better way to preserve file ownership of config.xml.
            runAsGroup: 1000
          command:
            - /bin/sh
            - -c
            - |
              if ! [ -e "/config/network.xml" ] ; then
                  echo "No network.xml found, creating minimal config."
                  cat <<EOF >/config/network.xml
              <Config>
                <BindAddress>*</BindAddress>
                <RequireHttps>false</RequireHttps>
                <InternalHttpPort>8096</InternalHttpPort>
                <InternalHttpsPort>8920</InternalHttpsPort>
                <PublicHttpPort>8096</PublicHttpPort>
                <PublicHttpsPort>8920</PublicHttpsPort>
                <BaseUrl>/</BaseUrl>
              </Config>
              EOF
              fi

              xmllint --shell /config/network.xml << EOF
              cd /NetworkConfiguration/BaseUrl
              {{- if eq $.Values.baseUrl "/" }}
              set /
              {{- else }}
              set {{ .Values.baseUrl | trimPrefix "/"}}
              {{- end }}
              save
              EOF
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        {{- if eq .Values.storage.data.type "hostPath" }}
        - name: data
          hostPath:
            path: {{ required "You need to set a path to the data directory! storage.data.path" .Values.storage.data.path }} # directory location on host
            type: Directory # this field is optional
        {{- else }}
          {{ fail "A valid .Values.storage.data.type needs to be set!"}}
        {{- end }}
        {{- if eq .Values.storage.config.type "hostPath" }}
        - name: config
          hostPath:
            path: {{ required "You need to set a path to the config directory! storage.config.path" .Values.storage.config.path }} # directory location on host
            type: Directory # this field is optional
        {{- else }}
          {{ fail "A valid .Values.storage.config.type needs to be set!"}}
        {{- end }}
        {{- if .Values.hardwareAcceleration.intel.enabled }}
        - name: render-device
          hostPath:
            path: {{ required "You need to define the render device path." .Values.hardwareAcceleration.intel.renderDevicePath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
