apiVersion: v2
name: arch-qbittorrentvpn
description: qBittorrent is a bittorrent client programmed in C++ / Qt that uses libtorrent (sometimes called 
  libtorrent-rasterbar) by Arvid Norberg. It aims to be a good alternative to all other bittorrent clients out there.
  qBittorrent is fast, stable and provides unicode support as well as many features.
  
  This Docker includes OpenVPN and WireGuard to ensure a secure and private connection to the Internet, including use of iptables to prevent IP leakage when the tunnel is down.

type: application
version: 0.1.2
appVersion: "5.0.3-1-01"
