apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prowlarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowlarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prowlarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
      initContainers:
      {{- if eq (.Values.config).AuthenticationMethod "External" }}
        - name: config
          image: pipelinecomponents/xmllint:0.8.1
          securityContext:
            runAsUser: 1000 # Find a better way to preserve file ownership of config.xml.
            runAsGroup: 1000
          command:
            - /bin/sh
            - -c
            - |
              if ! [ -e "/config/config.xml" ] ; then
                  echo "No config.xml found, creating minimal config."
                  cat <<EOF >/config/config.xml
              <Config>
                <BindAddress>*</BindAddress>
                <Port>9696</Port>
                <SslPort>6969</SslPort>
                <EnableSsl>False</EnableSsl>
                <AuthenticationMethod>None</AuthenticationMethod>
                <UrlBase>prowlarr</UrlBase>
              </Config>
              EOF
              fi
              
              xmllint --shell /config/config.xml << EOF
              cd /Config/AuthenticationMethod
              set External
              save
              EOF
          volumeMounts:
            - mountPath: /config
              name: config
      {{- end }}
      volumes:
        {{- if eq .Values.storage.config.type "hostPath" }}
        - name: config
          hostPath:
            path: {{ required "You need to set a path to the config directory! storage.config.path" .Values.storage.config.path }} # directory location on host
            type: Directory # this field is optional
        {{- else }}
          {{ fail "A valid .Values.storage.config.type needs to be set!"}}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
